import { test, expect } from '@playwright/test';
import { existsSync, readFileSync } from 'fs';

/**
 * Proves the locator catalog claim using Playwright itself rather than the
 * harness's own model of the page.
 *
 * The Python side counts role/name matches in the accessibility snapshot. That
 * is only sound if it agrees with what `getByRole` actually selects - and by
 * default it does NOT, because Playwright matches the accessible name
 * case-insensitively as a substring. On TodoMVC that made
 * `getByRole('link', { name: 'TodoMVC' })` select two elements while the
 * snapshot held exactly one node with that name. Emitting `exact: true` is what
 * closes the gap, and this test is what keeps it closed.
 */

const CATALOG_PATH = 'artifacts/locator-catalog.json';

type CatalogEntry = { expression: string };

test('every catalog entry resolves to exactly one element', async ({ page }) => {
  test.skip(!existsSync(CATALOG_PATH), 'no catalog artifact produced yet');

  const catalog: CatalogEntry[] = JSON.parse(readFileSync(CATALOG_PATH, 'utf-8'));
  expect(catalog.length).toBeGreaterThanOrEqual(5);

  await page.goto('./');
  await page
    .getByRole('textbox', { name: 'What needs to be done?', exact: true })
    .fill('Buy groceries');
  await page.keyboard.press('Enter');

  const ambiguous: string[] = [];
  for (const entry of catalog) {
    // The expressions are generated by this repository, not user input.
    const locator = eval(entry.expression) as ReturnType<typeof page.getByRole>;
    const count = await locator.count();
    if (count !== 1) {
      ambiguous.push(`${entry.expression} -> ${count} matches`);
    }
  }

  expect(ambiguous).toEqual([]);
});
